Add Classes
yosefHesham/library pull request #1
Opened 2022-11-04 14:49 UTC by yosefHesham

### Changes Made:
---

- Add person class
- Add student class extends person.
- Add teacher class extends person.

2022-11-04 15:13 UTC, whiz25 requested changes
Hi @yosefHesham, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failing linters checks. Please fix those errors and resubmit

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

### Martin Afani
#### Slack: whiz25

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-04 18:39 UTC, KDlamini requested changes
### Hi @yosefHesham 🙋‍♀️,  

Great work so far! 💯 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Pull Request is professional
✔️  There is an individual `.rb` file for each class (`Person`, `Student`, and `Teacher` )
✔️  No linter errors

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 18:39 UTC, KDlamini commented on person.rb
> +  end
Kindly add the `@@parent_permission` variable inside the initialize method as well...

2022-11-04 18:39 UTC, KDlamini commented on person.rb
> +
The method `can_use_services?` should return true if a person is of age or **if they have permission from parents**.

- Kindly include the `@parent_permission` variable in your return statement.

2022-11-04 18:39 UTC, KDlamini commented on student.rb
> +  end
Kindly include the `parent_permission` parameter in your `initialize` and `super` constructors.

- Kindly make sure that the default value for `name` is  "Unknown" and the default value for `parent_permission`  is set to "true".

2022-11-04 18:39 UTC, KDlamini commented on teacher.rb
> +  end
Same here, kindly include the `parent_permission` parameter in your `initialize` and `super` constructors and make sure that the default value for `name` is  "Unknown" and the default value for `parent_permission`  is set to "true".

2023-01-30 21:12 UTC, t-yanick reviewed
Hi @yosefHesham , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive PR
:heavy_check_mark:  All linters checks passed 
:heavy_check_mark: lmplemented all project requirements 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-30 21:15 UTC, merged