Association
yosefHesham/library pull request #3
Opened 2023-02-01 20:52 UTC by yosefHesham

**Changes Made:**

- Created book class.
- Created rental class.
- Created classroom class.
- Implemented relationships between classes.

2023-02-01 22:14 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @yosefHesham , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 22:14 UTC, bobb-Rob commented on classroom.rb
> +  attr :label
- [x] Great work on this project. According to the project requirement, you should create _**setter**_ and **_getter_** for `@label`.  This `attr :label` currently sets only **_getter_**. Please fix this.

Project requirement | 1
--- | ---
![image](https://user-images.githubusercontent.com/84156714/216168193-5287d257-f071-49bd-92be-3517fd947a58.png) 

- In this class too, you should have a **_getter_** for `:students`.
```ruby
attr_reader :students
```

2023-02-01 22:14 UTC, bobb-Rob commented on student.rb
>      @classroom = classroom
- [x] You are expected to implement a **_belongs-to_** relationship in this class. This `@classroom = classroom` and `classroom.add_student(self)` should be in a method called `classroom`. Example 👇🏾 

```ruby
def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

And, it should have a getter method using `attr_reader`.
```ruby
attr_reader :classroom
```

Link to the article with examples: https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships

2023-02-01 22:14 UTC, bobb-Rob commented on book.rb
> +  end
- [ ] Line 16 means you are assigning **_self_** to `rental.person`, which I think is abnormal. Please go through [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) from the example in a previous lesson. And try to implement this `add_rental` method correctly.

2023-02-01 22:14 UTC, bobb-Rob commented on book.rb
> +  attr :title, :author
- [ ] You are expected to have both **_Setters_** and **_getters_** for instance variables (remember about attr_accessor).
This `attr :title, :author` is similar to `attr_reader`, which is only **_getter_**. 

```ruby
attr_accessor :title, :author, :rentals
```

2023-02-01 22:14 UTC, bobb-Rob commented on rental.rb
> +  attr :date, :book, :person
- [ ] You are expected to have both **_Setters_** and **_getters_** for instance variables (remember about attr_accessor).
This `attr :date, :book, :person` is similar to `attr_reader`, which is only **_getter_**. 

```ruby
attr_accessor :date, :book, :person
```

2023-02-02 21:33 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @yosefHesham,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-02-02 21:54 UTC, merged